### ISSUE TITLE
OnOtherInstance is not working anymore in Lazarus 1.7 (trunk)

### ISSUE THREAD

**Issue by PascalRiekenberg** [blikblum/luipack#20]
OnOtherInstance doesn't get called on the first instance, though second instance gets terminated.

**Comment by PascalRiekenberg** [comment]
[UniqueInstanceTest.zip](https://github.com/blikblum/luipack/files/525831/UniqueInstanceTest.zip)

**Comment by PascalRiekenberg** [comment]
Here is a patch:
[uniqueinstance.patch.zip](https://github.com/blikblum/luipack/files/527524/uniqueinstance.patch.zip)
See: http://mantis.freepascal.org/view.php?id=30434

**Comment by blikblum** [comment]
Fixed. Nest time, please open a Pull Request
