### ISSUE TITLE
Project "testinstance.lpi" just not working

### ISSUE THREAD

**Issue by JohnML1** [blikblum/luipack#22]
Lazarus 1.9.0 trunk FPC 3.0.2 i386-win32-win32/win64

compiled \uniqueinstance\trunk\testcomponent\testinstance.lpi

started App second time, Listbox does not show anything.

Test with trunk uniqueinstance today.

I remember a working uniqueinstance ?!!

**Comment by JohnML1** [comment]
see:
http://forum.lazarus.freepascal.org/index.php/topic,34394.msg225343.html#msg225343

thats ok for Windows, didn't test for Linux

**Comment by JohnML1** [comment]
no, \testinstance.lpi still not working

**Comment by blikblum** [comment]
Already fixed
