### ISSUE TITLE
UniqueInstance instance created during runtime fails

### ISSUE THREAD

**Issue by CCRDude** [blikblum/luipack#24]
After the recent update to the package UniqueInstance in package manager, I've updated my code to use the component, trying to keep code out of my .lpr to keep that clean.

I now noticed that it simply fails. Found the reason: the component will only perform it's operation in the overridden protected method "Loaded". For a dynamically created instance, this will never be called.

I need to create it dynamically, since my form is just an app frameworks form that uses a class function to determine different Instance IDs per app.

As a workaround, I'm now using UniqueInstanceRaw.InstanceRunning(), which works fine, but I would like to recommend that the components magic should be triggered based on the setter of the Enabled property as an alternative to the designtime support only Loaded method.

I can create the patch since this looks quite simple, but wanted to communicate here first before putting effort into it.

**Comment by blikblum** [comment]
>As a workaround, I'm now using UniqueInstanceRaw.InstanceRunning(), which works fine, but I would like to recommend that the components magic should be triggered based on the setter of the Enabled property as an alternative to the designtime support only Loaded method.

The component is supposed to be used on design time and raw in runtime. Creating the server in Enabled is not good practice. If you still need to use it in runtime you can call Loaded yourself

**Comment by CCRDude** [comment]
Writing a component that cannot be dynamically created is not a good practice either. Writing a component that does not behave as expected without returning an error is not a good practice either. See, speaking about bad practices is easier than finding good ones ;)

Obviously I can't call `Loaded`, since it's protected. That's why I recommended to move the initialization code into a separate, public, method. That could then be called by Loaded, or by the user (or by the first SetEnabled).
