### ISSUE TITLE
UniqueInstance needs new event

### ISSUE THREAD

**Issue by Alexey-T** [blikblum/luipack#28]
https://forum.lazarus.freepascal.org/index.php?topic=50119.msg365298#msg365298
Can you add it?

**Comment by Alexey-T** [comment]
it is almost ok.
now I think that CudaText needs another change in UniqInst.
my app calls Loaded

a) we need to move Loaded from 'protected' to 'public' (app needs TUniqIntanceHack type)
b) we need Loaded with parameter - "const array of string".

so Cud will prepare this 'array of string' w/o events. and give it to Loaded().

**Comment by blikblum** [comment]
Loaded is called by lcl without parameters so It cannot be changed.

Please create a simple example so we evaluate the use case

**Comment by Alexey-T** [comment]
pseudo code -
```
var p: array of string;

SetLength(p, ParamCount);
for i:= 1 to ParamCount do
  p[i-1]:= mydir+'/'+ParamStr(i);

UniqInst.NewLoadedNeeded(p);
```

**Comment by blikblum** [comment]
You can already mutate the command line parameter using `OnPrepareParam` that is called internally by `Loaded`, so no need to a new Loaded method

**Comment by blikblum** [comment]
```pascal
TForm.PrepareParam(Sender : TObject; var Param: String);
begin
  Param := mydir+'/'+ Param;
end;
```

**Comment by Alexey-T** [comment]
Ok thanks.

**Comment by blikblum** [comment]
If you want to remove an Param, set Param to ''
