### ISSUE TITLE
My fix to avoid receiving Timer-event on CudaText closing, and the crash

### ISSUE THREAD

**Issue by Alexey-T** [blikblum/luipack#32]
https://github.com/Alexey-T/CudaText/commit/87e2bffe2c4d49dbb0ea3e1352f81f09caa0b81f

This is a patch in CudaText's copy of UniqInstance. You see that I moved Timer object to class fields, and I disable this timer in Destroy.
crash was visible when I debugged the CudaText.

**Comment by blikblum** [comment]
Please open a Pull Request: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Alexey-T** [comment]
sorry, for PR I would need to get your code and test it. no time.

**Comment by blikblum** [comment]
Sorry, this is how collaborating in Github works.

**Comment by Alexey-T** [comment]
no, it don't work always this way. I sometimes get patches via email. 

if you don't want to improve the upstream code, do it as you wish.

**Comment by blikblum** [comment]
Opening Pull Requests is pretty easy, i've done literally hundreds of times to different repositories.

I'm just asking to do what i do to other projects and what is default in github community

![image](https://user-images.githubusercontent.com/3047126/126052006-7a56a8c7-bdef-43e8-b9db-5dc0b3bae941.png)

**Comment by Alexey-T** [comment]
it's easy if I can tests the resulting pascal file, how it's compiled, how it works, but I am busy.
