### ISSUE TITLE
Cannot compile CairoLCL: Identifier not found TGtk2DeviceContext

### ISSUE THREAD

**Issue by rchastain** [blikblum/luipack#35]
Hello!

I try to install TCairoPaintBox on Lazarus 2.2.4 (Linux) and I get an error here:

```
// cairolcl.inc
function CreateSurfaceFromDC(DC: HDC): Pcairo_surface_t;
var
  DeviceContext: TGtk2DeviceContext absolute DC;
```
I replaced _TGtk2DeviceContext_ with _TGtkDeviceContext_ and it seems to solve the problem.

Regards.

Roland

**Comment by blikblum** [comment]
Can you create a Pull Request?

**Comment by rchastain** [comment]
Here you are.

https://github.com/blikblum/luipack/pull/36

I am not a _git_ expert, so I hope that this is what you expect.
